image: inoutput/laravel-bitbucket-pipelines

pipelines:
  branches:
    master:
      - step:
          caches:
          - composer
          - node
          script:
            - apt-get install openssh-client
            - composer install
            - yarn install
            - yarn run prod
            - touch .env
            - echo "APP_NAME=\"$APP_NAME\"" >> .env
            - echo "APP_ENV=production" >> .env
            - echo "APP_KEY=$(php artisan key:generate --show)" >> .env
            - echo "APP_DEBUG=false" >> .env
            - echo "APP_URL=$APP_URL" >> .env
            - echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> .env
            - echo "CLIENT_ID=$CLIENT_ID" >> .env
            - echo "CLIENT_SECRET=$CLIENT_SECRET" >> .env
            - echo "SC_BG=$SC_BG" >> .env
            - echo "SC_BP=$SC_BP" >> .env
            - echo "SC_SPO2=$SC_SPO2" >> .env
            - echo "SC_SUBJECT=$SC_SUBJECT" >> .env
            - echo "SC_WEIGHT=$SC_WEIGHT" >> .env
            - echo "SV_BG=$SV_BG" >> .env
            - echo "SV_BP=$SV_BP" >> .env
            - echo "SV_SPO2=$SV_SPO2" >> .env
            - echo "SV_SUBJECT=$SV_SUBJECT" >> .env
            - echo "SV_WEIGHT=$SV_WEIGHT" >> .env
            - echo "REDIRECT_URI=$REDIRECT_URI" >> .env
            - echo "DB_CONNECTION=mysql" >> .env
            - echo "DB_HOST=$DB_HOST" >> .env
            - echo "DB_PORT=3306" >> .env
            - echo "DB_DATABASE=$DB_DATABASE" >> .env
            - echo "DB_USERNAME=$DB_USERNAME" >> .env
            - echo "DB_PASSWORD=$DB_PASSWORD" >> .env
            - echo "BROADCAST_DRIVER=log" >> .env
            - echo "CACHE_DRIVER=file" >> .env
            - echo "SESSION_DRIVER=file" >> .env
            - echo "SESSION_LIFETIME=120" >> .env
            - echo "QUEUE_DRIVER=sync" >> .env
            - echo "MAIL_DRIVER=smtp" >> .env
            - echo "MAIL_HOST=$MAIL_HOST" >> .env
            - echo "MAIL_PORT=$MAIL_PORT" >> .env
            - echo "MAIL_USERNAME=$MAIL_USERNAME" >> .env
            - echo "MAIL_PASSWORD=$MAIL_PASSWORD" >> .env
            - echo "MAIL_ENCRYPTION=$MAIL_ENCRYPTION" >> .env
            - echo "ADMIN_USERNAME=ADMIN_USERNAME" >> .env
            - echo "ADMIN_EMAIL=ADMIN_EMAIL" >> .env
            - echo "ADMIN_PASSWORD=ADMIN_PASSWORD" >> .env
            - touch release.tar.gz
            - tar -czf release.tar.gz . --exclude=./release.tar.gz
            - scp release.tar.gz $SSH_USER@$SSH_HOST:/home/$SSH_USER
            - ssh $SSH_USER@$SSH_HOST "tar -xf release.tar.gz -C $APP_ROOT && rm -Rf release.tar.gz"